#!/bin/bash

echo 'Build successful! Deploying iamges to Docker repository'
docker login $DOCKER_REPOSITORY_DOMAIN  --username $CI_USER --password $CI_PASSWORD

echo 'Deploying XRAY classifier to Docker repository'
docker tag $XRAY_CLASSIFIER_IMAGE_NAME:$IMAGE_TAG $DOCKER_REPOSITORY_DOMAIN/$CI_USER/$XRAY_CLASSIFIER_IMAGE_NAME:$IMAGE_TAG
docker push $DOCKER_REPOSITORY_DOMAIN/$CI_USER/$XRAY_CLASSIFIER_IMAGE_NAME:$IMAGE_TAG

echo 'Deploying MRI classifier to Docker repository'
docker tag $MRI_CLASSIFIER_IMAGE_NAME:$IMAGE_TAG $DOCKER_REPOSITORY_DOMAIN/$CI_USER/$MRI_CLASSIFIER_IMAGE_NAME:$IMAGE_TAG
docker push $DOCKER_REPOSITORY_DOMAIN/$CI_USER/$MRI_CLASSIFIER_IMAGE_NAME:$IMAGE_TAG

echo 'Deploying Object detection algorithm to Docker repository'
docker tag $OBJECT_DETECTION_IMAGE_NAME:$IMAGE_TAG $DOCKER_REPOSITORY_DOMAIN/$CI_USER/$OBJECT_DETECTION_IMAGE_NAME:$IMAGE_TAG
docker push $DOCKER_REPOSITORY_DOMAIN/$CI_USER/$OBJECT_DETECTION_IMAGE_NAME:$IMAGE_TAG